---
- name: Setup vmstorage
  ansible.builtin.include_tasks:
    file: vmstorage.yml
    apply:
      become: true

- name: Setup vminsert
  ansible.builtin.include_tasks:
    file: vminsert.yml
    apply:
      become: true

- name: Setup vmselect
  ansible.builtin.include_tasks:
    file: vmselect.yml
    apply:
      become: true

- name: Setup vmauth
  ansible.builtin.include_tasks:
    file: vmauth.yml
    apply:
      become: true
  tags:
    - vmauth

- name: Setup keepalived
  ansible.builtin.include_tasks:
    file: keepalived.yml
    apply:
      become: true
