---
- name: Setup vmstorage
  ansible.builtin.include_tasks:
    file: vmstorage.yml
    apply:
      become: true

- name: Setup vminsert
  ansible.builtin.include_tasks:
    file: vminsert.yml
    apply:
      become: true

- name: Setup vmselect
  ansible.builtin.include_tasks:
    file: vmselect.yml
    apply:
      become: true
