---
- name: Create vmstorage directory
  ansible.builtin.file:
    path: "{{ vmstorage.host_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Template systemd unit file
  ansible.builtin.template:
    src: vmstorage.service.j2
    dest: /etc/systemd/system/vmstorage.service
    mode: '0644'

- name: Enable and start vmstorage
  ansible.builtin.systemd:
    name: vmstorage
    daemon_reload: true
    state: started
